# Generated by Django 6.0.3 on 2026-05-07 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("faculty_email", models.EmailField(max_length=254, unique=True)),
                ("faculty_name", models.CharField(max_length=100)),
                ("faculty_id", models.CharField(max_length=4, unique=True)),
                (
                    "faculty_designation",
                    models.CharField(
                        choices=[
                            ("Professor", "Professor"),
                            ("Guest Lecturer", "Guest Lecturer"),
                            ("Assistant Professor", "Assistant Professor"),
                            ("HOD - IT", "HOD - IT"),
                            ("HOD - Management", "HOD - Management"),
                            ("IT / Skill Trainer", "IT / Skill Trainer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("optionselected", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLogsFaculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("Login", "Login"), ("Logout", "Logout")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appFaculty.faculty",
                    ),
                ),
            ],
        ),
    ]
