# Generated by Django 6.0.3 on 2026-05-08 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appFaculty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyAssignedSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=200)),
                ("subject_code", models.CharField(max_length=20)),
                ("semester", models.CharField(max_length=20)),
                ("session", models.CharField(max_length=20)),
                ("date_assigned", models.DateTimeField(auto_now_add=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        db_column="faculty_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_subjects",
                        to="appFaculty.faculty",
                        to_field="faculty_id",
                    ),
                ),
            ],
        ),
    ]
