# Generated by Django 6.0.3 on 2026-05-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appFaculty", "0003_faculty_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="faculty_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
