# Generated by Django 6.0.3 on 2026-05-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appFaculty", "0004_alter_faculty_faculty_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyWiseAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                ("course_name", models.CharField(max_length=50)),
                ("faculty_id", models.CharField(max_length=20)),
                ("faculty_name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=200)),
                ("attendance", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentWiseAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                ("course_name", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=200)),
                ("faculty_id", models.CharField(max_length=20)),
                ("student_id", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
