# Generated by Django 6.0.3 on 2026-05-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminRoles",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ErpAdmin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "roles",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appErpAdmin.adminroles",
                    ),
                ),
            ],
        ),
    ]
