# Generated by Django 6.0.3 on 2026-05-10 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appErpAdmin", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="erpadmin",
            old_name="roles",
            new_name="role",
        ),
    ]
