# Generated by Django 6.0.3 on 2026-05-10 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appErpAdmin", "0002_rename_roles_erpadmin_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "course_name",
                    models.CharField(
                        choices=[
                            ("BCA", "BCA"),
                            ("BSC IT", "BSC IT"),
                            ("BBA", "BBA"),
                            ("BCOM", "BCOM"),
                            ("PGDM", "PGDM"),
                            ("MBA", "MBA"),
                            ("MCA", "MCA"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "university_name",
                    models.CharField(
                        choices=[("AKU", "AKU"), ("PPU", "PPU")],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseSessions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                ("complete_name", models.CharField(max_length=255, unique=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appErpAdmin.courses",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appErpAdmin.university",
                    ),
                ),
            ],
        ),
    ]
