# Generated by Django 6.0.3 on 2026-05-12 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appErpAdmin", "0003_courses_university_coursesessions"),
        ("appStudent", "0005_delete_studentcourseenrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appErpAdmin.coursesessions",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appStudent.student",
                    ),
                ),
            ],
        ),
    ]
