# Generated by Django 6.0.3 on 2026-05-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("student_id", models.CharField(max_length=12, unique=True)),
                ("course", models.CharField(max_length=6)),
                ("session", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="students/")),
            ],
        ),
    ]
