# Generated by Django 6.0.3 on 2026-05-07 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appStudent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(
                default=django.utils.timezone.now, max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
