# Generated by Django 6.0.3 on 2026-05-07 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appStudent", "0002_student_date_created_student_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("Login", "Login"), ("Logout", "Logout")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appStudent.student",
                    ),
                ),
            ],
        ),
    ]
