# Generated by Django 6.0.3 on 2026-05-10 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appErpAdmin", "0003_courses_university_coursesessions"),
        ("appStudent", "0003_activitylogs"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentCourseEnrollment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "course_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appErpAdmin.coursesessions",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appStudent.student",
                    ),
                ),
            ],
        ),
    ]
