# Generated by Django 6.0.3 on 2026-05-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appStudent", "0004_studentcourseenrollment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentCourseEnrollment",
        ),
    ]
